Subindo o guia de configurando o seu github
Insper/robotica-computacional pull request #1
Opened 2022-12-13 18:11 UTC by liciascl

2022-12-20 17:22 UTC, igordsm requested changes

2022-12-20 17:22 UTC, igordsm commented on docs/guias-infra/configure_seu_github/configure_seu_github.md
> +# Configure o seu GitHub
Mudar o nome da página para `index.md`. Assim o endereço ficaria certinho como `guias-infra/configure_seu_github/`.

2022-12-20 17:22 UTC, igordsm commented on docs/guias-infra/configure_seu_github/configure_seu_github.md
> +Boas noticias, não precisa instalar o GitHub, deixamos isso pronto pra você, porém, algumas configurações só você pode fazer, te mostramos neste guia quais são os passos para fazer as configurações n
Isso começou meio estranho... Que tal explicar em duas frases o que é  `git` e *Github*?

2022-12-20 17:22 UTC, igordsm commented on docs/guias-infra/configure_seu_github/configure_seu_github.md
> +A primeira coisa que devemos fazer antes de começar a usar o GitHub é configurar o **nome de usuário** e **endereço de e-mail**. Isto é importante porque cada *commit*  usa esta informação, e ela é c
Já imaginamos que eles tem cadastro no github aqui, certo?

2022-12-20 17:22 UTC, igordsm commented on docs/guias-infra/configure_seu_github/configure_seu_github.md
> +Abra um terminal usando o atalho Ctrl + T, então use os comando a seguir para configurar o seu user name e seu email:
Não era Super+T o atalho?

2022-12-20 17:22 UTC, igordsm commented on docs/guias-infra/configure_seu_github/configure_seu_github.md
> +💡Não precisa colocar o seu login do GitHub ao configurar o user.name, pode ser o seu nome sem problemas
Usar !!! tip aqui

2022-12-20 17:22 UTC, igordsm commented on docs/guias-infra/configure_seu_github/configure_seu_github.md
> +Se você precisar substituir os dados de usuário e email para um projeto específico, você pode rodar o mesmo comando **sem a opção** `--global` dentro do projeto específico, então a configuração será
Bom!

2022-12-20 17:22 UTC, igordsm commented on docs/guias-infra/configure_seu_github/configure_seu_github.md
> +### Seu Editor
Eu pularia isso e deixaria o nano mesmo. Se é para usar o VSCode eu já sugeriria usar a interface dele mesmo para fazer os commits.

2022-12-20 17:22 UTC, igordsm commented on docs/guias-infra/configure_seu_github/configure_seu_github.md
> +para saber detalhes e diferenças entre os tipos de tokens do GitHub e porque eles existem (Spoiler > é por segurança) consulte a [documentação aqui](https://docs.github.com/en/authentication/keeping-
"para" => "Para" . Eu juntaria os dois parágrafos em um só, mas não faço questão.

2022-12-20 17:22 UTC, igordsm commented on docs/guias-infra/configure_seu_github/configure_seu_github.md
> +Na página do seu GitHub, clique na sua foto e depois encontre a opção “Configuração” ou **“Settings”**
**Configuração**

2022-12-20 17:22 UTC, igordsm commented on docs/guias-infra/configure_seu_github/configure_seu_github.md
> +![Untitled](imgs/Untitled.png)
renomear imagens :+1:

2022-12-20 17:22 UTC, igordsm commented on docs/guias-infra/configure_seu_github/configure_seu_github.md
> +Atualmente, o GitHub oferece suporte a dois tipos de tokens, nós vamos de clássico.
Aqui eu esperaria saber quais são os dois tipos de tokens. Ou até mesmo o que é o token e pra que ele serve. Pode ser uma descrição rápida de uma frase.

2022-12-20 17:22 UTC, igordsm commented on docs/guias-infra/configure_seu_github/configure_seu_github.md
> +💡Você pode criar quantos tokens você quiser, apenas certifique-se de salvar a chave hash com carinho.
usar `!!! tip` aqui.

2022-12-20 17:22 UTC, igordsm commented on docs/guias-infra/configure_seu_github/configure_seu_github.md
> +Role a página até o final e encontre o botão Generate token
**Generate Token** => para ficar consistente com os outros.

2022-12-20 17:22 UTC, igordsm commented on docs/guias-infra/configure_seu_github/configure_seu_github.md
> +💡Você precisa estar dentro de um repositório git para conseguir armazenar a sua credencial.
Que tal usar `!!! warning` aqui?

2022-12-20 17:22 UTC, igordsm commented on docs/guias-infra/configure_seu_github/configure_seu_github.md
> +`Username: SeuUserNameAqui`
Usar três crases para criar um box de várias linhas. Fica mais bonitinho.

2022-12-20 17:22 UTC, igordsm commented on docs/guias-infra/configure_seu_github/configure_seu_github.md
> +Recomendamos fortemente que você se inscreva na atividade complementar de Git para aprender a usar essa ferramenta, vamos utilizar muito daqui pra frente.
Usar `!!! tip` nisso. Talvez até um `!!! important` ?

2023-01-11 19:48 UTC, liciascl commented on docs/guias-infra/configure_seu_github/configure_seu_github.md
> +# Configure o seu GitHub
'configure_seu_github.md' -> 'docs/guias-infra/ssd-linux/git-e-github/index.md'

2023-01-11 19:50 UTC, liciascl commented on docs/guias-infra/configure_seu_github/configure_seu_github.md
> +A primeira coisa que devemos fazer antes de começar a usar o GitHub é configurar o **nome de usuário** e **endereço de e-mail**. Isto é importante porque cada *commit*  usa esta informação, e ela é c
sim, eles usam o git no segundo semestre

2023-01-16 13:36 UTC, merged