subindo guia de introdução ao linux e comandos basicos via terminal
Insper/robotica-computacional pull request #2
Opened 2022-12-13 18:30 UTC by liciascl

2022-12-24 18:14 UTC, igordsm requested changes
Observações gerais: 

* cuidado com os tamanhos de imagens. Tem muitos que parecem bugados.
* nomes de arquivos poderiam ser mais descritivos
* usar mais admonitions

No notion várias das coisas que estão aqui renderizam bem, porém no mkdocs temos outras soluções que ficam melhores. Vou ir apontando elas conforme o material for tomando corpo.

2022-12-24 18:14 UTC, igordsm commented on docs/guias-infra/comece_por_aqui/comece_por_aqui.md
> +# Comece por aqui!
Trocar o nome o arquivo para ˋindex.mdˋ. O título da página em geral vem do primeor título H1, mas dá para mudar tbm no ˋmkdocs.ymlˋ.

2022-12-24 18:14 UTC, igordsm commented on docs/guias-infra/comece_por_aqui/comece_por_aqui.md
> + **⚠️ Caso você possua um MacBook Intel, clique aqui**
Não tem Links aqui. Eu sugeriria tbm usar algum dos admonitions tipo warning para dar destaque a essas mensagens.

2022-12-24 18:14 UTC, igordsm commented on docs/guias-infra/comece_por_aqui/comece_por_aqui.md
> +## Essa será a sequência de passos deste tutorial
Eu tiraria o H2 aqui e deixaria como texto normal... Tb deixaria a lista direto sem os negritos. Quando renderiza fica bem legal.

2022-12-24 18:14 UTC, igordsm commented on docs/guias-infra/comece_por_aqui/comece_por_aqui.md
> +Com o Windowns inicializado, pesquise por **Bitlocker** no menu iniciar.
Explicar um pouquinho o que seria o BitLocker. Meu note não tem isso, então achei que poderia ter um parágrafo de introdução explicando o que é e quepode não precisar fazer isso.

2022-12-24 18:14 UTC, igordsm commented on docs/guias-infra/comece_por_aqui/comece_por_aqui.md
> +![img1](imgs/img1.png)
que tal trocar para passo1.png e afins?

2022-12-24 18:14 UTC, igordsm commented on docs/guias-infra/comece_por_aqui/comece_por_aqui.md
> +⚠️ Pesquise no Google a tecla de acesso a **BIOS** e a tecla de acesso ao **Boot Menu** do seu notebook
Usar um !!! Tip aqui

2022-12-24 18:14 UTC, igordsm commented on docs/guias-infra/comece_por_aqui/comece_por_aqui.md
> +Para falar a verdade, eu também não sei, cada fabricante tem uma tecla diferente para acessar a BIOS,  recomendo que **utilize o Google** para descobrir a sua, caso você encontre dificuldades, procur
Aqui ficou informal demais. Na minha opinião, em geral usar primeira pessoa é OK para textos autorais em que só uma pessoa contribui. Quando é algo mais coletivo eu tenderia a usar imperativo.

2022-12-24 18:14 UTC, igordsm commented on docs/guias-infra/comece_por_aqui/comece_por_aqui.md
> +**Para acessar a BIOS, é necessário:**
Mesma coisa da outra lista

2022-12-24 18:14 UTC, igordsm commented on docs/guias-infra/comece_por_aqui/comece_por_aqui.md
> +## **Inicializando o SSD**
Se usar ˋ##ˋnão precisa do negrito

2022-12-24 18:14 UTC, igordsm commented on docs/guias-infra/comece_por_aqui/comece_por_aqui.md
> +  **1.**  Desligue o notebook;
Lista com negrito e indent. Provavelmentenão vai renderizar correto.

2022-12-24 18:14 UTC, igordsm commented on docs/guias-infra/comece_por_aqui/comece_por_aqui.md
> + ⚠️  **A senha de acesso está disponivel no folder que acompanha o SSD, recomendamos fortemente que troque a senha, no próximo tutorial eu te mostro como fazer isso.**
Mesma coisa do outro. Aqui poderíamos trocar pela primeira pessoa do plural. " Eu te mostro" -> "trocaremos sua senha" . Usar algum admonition. Warning talvez?

2022-12-24 18:14 UTC, igordsm commented on docs/guias-infra/comece_por_aqui/comece_por_aqui.md
> +<img src="https://github.com/Insper/robotica-computacional/blob/Comece_por_aqui/imgs/img12.png" width="750" height="750" />
E esse HTML aqui? 😭

2022-12-24 18:14 UTC, igordsm commented on docs/guias-infra/guia-linux/guia-linux.md
> +
Trocar para ˋindex.mdˋ

2022-12-24 18:14 UTC, igordsm commented on docs/guias-infra/guia-linux/guia-linux.md
> +<kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>T</kbd>
Isso aqui funciona no mkdocs?

2022-12-24 18:14 UTC, igordsm commented on docs/guias-infra/guia-linux/guia-linux.md
> +O sistema operacional instalado no seu SSD é conhecido como **LINUX**, mas o termo correto é Ubuntu versão 20.04 o kernal sim, é o GNU/Linux. O kernel é o orquestrador do sistema operacional, ele uti
Apesar deu eu pessoalmente adorar essas conversas de história e software livre/open source, acho que esse não seria o melhor lugar para colocar isso. Talvez separar isso em um novo arquivo ˋum_pouco_de_historia.mdˋ e fazer um box bonitinho apontando para essa página. Seria legal fazer o aluno começar direto o conteúdo, já que esse é um guia de infra.

2022-12-24 18:14 UTC, igordsm commented on docs/guias-infra/comece_por_aqui/comece_por_aqui.md
> +Salves as alterações em **Aplly** e **Exit** para sair da BIOS e reiniciar o notebook.
"Salves" -> "Salve". **Apply**

2022-12-24 18:14 UTC, igordsm commented on docs/guias-infra/guia-linux/guia-linux.md
> +`APT` é um conjunto de ferramentas usadas pelo Linux para administrar os pacotes `.deb` de forma automática, é possível instalar, atualizar e remover programas e suas dependências via apt;
O aluno não sabeo que são pacotes ˋ.debˋ neste momento. Que tal " para administrar o sistema. E possível ..."

2022-12-24 18:14 UTC, igordsm commented on docs/guias-infra/guia-linux/guia-linux.md
> +
Antes de prosseguir, pode ser uma boa explicar o que é um pacote. Uma ou duas frases já bastam

2022-12-24 18:14 UTC, igordsm commented on docs/guias-infra/guia-linux/guia-linux.md
> +### Atualizar pacotes "já instalados"
Eu tiraria essas aspas. aqui.  O texto flui bem sem elas

2022-12-24 18:14 UTC, igordsm commented on docs/guias-infra/guia-linux/guia-linux.md
> +### Instalar pacotes via apt
Não seria melhor mover isso pra cima? O ˋapt installˋjá é usado acima, então pela sequência faria sentido isso aparecer antes.

2022-12-24 18:14 UTC, igordsm commented on docs/guias-infra/guia-linux/guia-linux.md
> +{width=100}
esse width jogado aqui parece errado 👀

2022-12-24 18:14 UTC, igordsm commented on docs/guias-infra/guia-linux/guia-linux.md
> +{width=800}
👀

2022-12-24 18:14 UTC, igordsm commented on docs/guias-infra/guia-linux/guia-linux.md
> +O comando **cd** é um dos comandos mais utilizados no terminal do Linux isso porque ele permite que acessemos um diretório especifico. Vamos acessar o nosso  repositorio de Elementos de Sistemas, e a
Sugiro indicar que **CD** vem de **C**hange **D**irectory

2022-12-24 18:14 UTC, igordsm commented on docs/guias-infra/guia-linux/guia-linux.md
> +> Dica:. Podemos apenas digitar o começo do comando e usar a tecla <kbd>TAB</kbd> para auto-completar.
usar !!! tip aqui

2022-12-24 18:14 UTC, igordsm commented on docs/guias-infra/guia-linux/guia-linux.md
> +Podemos verificar o caminho do diretório que estamos digitanto:
digitando

2022-12-24 18:14 UTC, igordsm commented on docs/guias-infra/guia-linux/guia-linux.md
> +> Toda vez que abrimos um novo terminal, ele é inicializado na home do usuário.
!!! tip

2022-12-24 18:14 UTC, igordsm commented on docs/guias-infra/guia-linux/guia-linux.md
> +O comando **ls** é utilizado pra visualizar o conteúdo de um diretório.
**ls** vem de **l**i**s**t

2022-12-24 18:14 UTC, igordsm commented on docs/guias-infra/guia-linux/guia-linux.md
> +> Dica:. Você sempre pode usar a tecla <kbd>TAB</kbd> para auto-completar os comandos.
!!! tip

2022-12-24 18:14 UTC, igordsm commented on docs/guias-infra/guia-linux/guia-linux.md
> +```
Eu chutaria que essas linhas vazias são renderizadas no resultado final. Eu tiraria

2022-12-24 18:14 UTC, igordsm commented on docs/guias-infra/guia-linux/guia-linux.md
> +Para copiar arquivos e diretorios, basta  digitar:
**cp** vem de **c**o**p**y

2022-12-24 18:14 UTC, igordsm commented on docs/guias-infra/guia-linux/guia-linux.md
> +### Comando "mv"
mv vem de move

2022-12-24 18:14 UTC, igordsm commented on docs/guias-infra/guia-linux/guia-linux.md
> +### Comando "mv"
isso está meio repetido. Faz sentido refrasear para ficar tudo em uma só seção

2022-12-24 18:14 UTC, igordsm commented on docs/guias-infra/guia-linux/guia-linux.md
> +### Comando "rm"
remove :)

2022-12-24 18:14 UTC, igordsm commented on docs/guias-infra/guia-linux/guia-linux.md
> +
Explicar o que é super usuário aqui. Na prática seria só tirar uma parte da explicação da seção de baixo para esta.

2022-12-24 18:14 UTC, igordsm commented on docs/guias-infra/guia-linux/guia-linux.md
> +A titulo de curiosidade, "sudo" significa **S**uper **U**ser **DO**. Quando executar comandos com sudo, será necessário informar a senha.
👍

2022-12-24 18:14 UTC, igordsm commented on docs/guias-infra/guia-linux/guia-linux.md
> +### Comando "chmod"
change mode -> mode é o nome do campo que guarda as permissões de um arquivo

2022-12-24 18:14 UTC, igordsm commented on docs/guias-infra/guia-linux/guia-linux.md
> +Se você não tem certeza se o dispositivo conectado a sua porta PCI foi reconhecido, use este comando e verifique o log do sistema;
Isso está certo? Fala de USB, mas usa lspci... Parece repetido da seção anterior tbm

2022-12-24 18:14 UTC, igordsm commented on docs/guias-infra/guia-linux/guia-linux.md
> +Para matar um processo, digite o comando abaixo, e o nome do software que deseja assassinar;
eu trocaria assassinar para finalizar

2022-12-24 18:14 UTC, igordsm commented on docs/guias-infra/guia-linux/guia-linux.md
> +Fontes:
Usar ˋ##ˋaqui tbm.

2022-12-24 18:14 UTC, igordsm commented on docs/guias-infra/guia-linux/guia-linux.md
> +**[Linux: conheça o Linux OS](https://www.redhat.com/pt-br/topics/linux)**
Criar lista de links ao invés de só por um por parágrafo.

2023-01-13 18:01 UTC, liciascl commented on docs/guias-infra/guia-linux/guia-linux.md
> +<kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>T</kbd>
não funciona </3

2023-01-16 14:26 UTC, igordsm commented on docs/guias-infra/ssd-linux/guia-linux/index.md
> +!!! tip "Caso tenha interesse em aprofundar alguns conceitos sobre o Sistema Operacional Linux, [clique aqui](um-pouco-de-historia.md)."
Os admonitions ficam mais bonitinhos se usar o seguinte formato:

```
!!! tip
    texto vai aqui. 
```

2023-01-16 14:27 UTC, igordsm commented on docs/guias-infra/ssd-linux/guia-linux/index.md
> +## Espero que você esteja se sentindo mais confortável para explorar e personalizar o seu Ubuntu. [No próximo guia](), vamos conhecer o robô simulado e o ROS, divirta-se!
O mkdocs já coloca no rodapé a navegação para os próximos guias. Não precisa incluir no fim esse tipo de texto. 

Além disso, eu tiraria o `##`

2023-01-23 12:08 UTC, merged