Meu SSD Subiu
Insper/robotica-computacional pull request #3
Opened 2022-12-13 18:59 UTC by rbcuenca

2022-12-19 16:43 UTC, igordsm requested changes

2022-12-19 16:43 UTC, igordsm commented on docs/guias-infra/Meu_SSD_subiu/Meu_SSD_subiu.md
> +# Meu SSD subiu, e agora?
Se chamarmos esse arquivo de index.md dá para o endereço ficar bonitinho (entrando direto em `guias-infra/Meu_SSD_subiu/` ).

2022-12-19 16:43 UTC, igordsm commented on docs/guias-infra/Meu_SSD_subiu/Meu_SSD_subiu.md
> +Você seguiu o tutorial anterior, conseguiu “bootar” o SSD no seu computador, excelente! Mas… e agora?? ;-) Vamos aos primeiros passos, de forma bem detalhada (pensando em você que nunca usou linux an
na parte do tutorial anterior, que tal colocar um link para ele? Eu sugeriria "tutorial anterior ([Boot com SSD](endereco aqui))" para ficar mais claro qual é o passo anterior.

2022-12-19 16:43 UTC, igordsm commented on docs/guias-infra/Meu_SSD_subiu/Meu_SSD_subiu.md
> +
Eu colocaria os passos aqui em uma lista numerada. Depois cada passo virar uma subseção, que nem está, ficou bom.

2022-12-19 16:43 UTC, igordsm commented on docs/guias-infra/Meu_SSD_subiu/Meu_SSD_subiu.md
> +![Untitled](imgs/Untitled.png)
Que tal trocar os nomes das imagens para `passo1.png`, `passo2.png` e por aí vai?

2022-12-19 16:43 UTC, igordsm commented on docs/guias-infra/Meu_SSD_subiu/Meu_SSD_subiu.md
> +A primeira configuração que recomendamos é trocar esta senha inicial. Para isso, você pode abrir o terminal (veja dois ícones de terminais na barra de atalhos). Você pode clicar no programa com o mou
Não sou contra usar o terminal aqui, mas seria legal fixar um deles. Por exemplo, Super+T abre o terminator? Se sim poderíamos já adotá-lo como padrão em tudo. 

Uma sugestão seria colocar um print aqui com o ícone dele. Eu sou visual, então ter o ícone me ajudaria a encontrar logo o programa.

2022-12-19 16:43 UTC, igordsm commented on docs/guias-infra/Meu_SSD_subiu/Meu_SSD_subiu.md
> +Com o terminal aberto (não importa qual dos dois você escolheu), você digitará o comando: `passwd` em seguida forneca a **senha atual** (fl1pfl0p) e depois a **nova senha**, lembrando que precisa ter
"você digitará" -> "digite"

2022-12-19 16:43 UTC, igordsm commented on docs/guias-infra/Meu_SSD_subiu/Meu_SSD_subiu.md
> +Algo que você precisa se habituar a usar é o terminal. Sim, no linux digitamos bastante e há algo importante neste caso, a tecla TAB é sua melhor amiga quando abrir o terminal! Ela sabe quase tudo!!
Usar o admonition tip para a dica do TAB fica bem legal. Algo como

!!! tip "Use o TAB"
    O terminal oferece sugestões para completar comandos quando apertamos a tecla TAB. Se houver uma só sugestão o comando já aparece inteiro. Se houver mais de uma é só pressionar TAB duas vezes que a lista de possibilidades é apresentada.

2022-12-19 16:43 UTC, igordsm commented on docs/guias-infra/Meu_SSD_subiu/Meu_SSD_subiu.md
> +Esta etapa não é difícil mas requer atenção em alguns detalhes. Você precisará usar uma rede diferente para esta disciplina, chamada **Robotica**. É nesta rede que nossos robôs se conectam para serem
Que tal "Configurar a rede não é difícil .... " 

Dado que vamos usar Adhoc, essa parte precisaria ser refeita. Estou OK em aprovar agora, mas isso entra na lista de ajustes para o semestre.

2022-12-19 16:43 UTC, igordsm commented on docs/guias-infra/Meu_SSD_subiu/Meu_SSD_subiu.md
> +Podemos concatenar os dois comandos utilizando `&&` no terminal. Desta forma podemos executar o update e o upgrade na mesma linha, como segue: `sudo apt update && sudo apt upgrade -y`.
Se tiverem pique, um tip diferenciando `&&` de `;` pode ser legal. (O primeiro só executa o segundo comando se o primeiro der certo. O segundo faz os dois sempre)

2022-12-19 16:43 UTC, igordsm commented on docs/guias-infra/Meu_SSD_subiu/Meu_SSD_subiu.md
> +Equipe 404
Aqui no fim não precisa "assinar" o documento. Eventualmente teremos uma página da equipe no site e carinhas das pessoas que editaram cada documento.

2022-12-19 16:43 UTC, igordsm commented on docs/guias-infra/Meu_SSD_subiu/Meu_SSD_subiu.md
> +Se você conseguiu seguir todos os passos até agora, o seu SSD já está pronto para ser utilizado. Como você utilizará linux em outras etapas do curso, a dica é usar o SSD para tudo neste semestre. Se
Pode ser uma boa aqui colocar um link para o próximo guia. Eu tbm tiraria essa parte: "Se você ficou com alguma dúvida ou algum passo não deu certo, nos procure no Laboratório de Informática - 404 Prédio 1 ou na sala definida para a aula de Robótica que auxiliaremos com este primeiro passo." Isso já vai ser enfatizado em aula, então não precisa aparecer novamente no guia.

2022-12-26 20:16 UTC, igordsm commented
Esse título me parece um pouco estranho. Que tal "Primeirospassos"?

2023-01-11 19:27 UTC, liciascl commented on docs/guias-infra/Meu_SSD_subiu/Meu_SSD_subiu.md
> +# Meu SSD subiu, e agora?
alterado para primeiros-passos/index.md

2023-01-11 19:27 UTC, liciascl commented on docs/guias-infra/Meu_SSD_subiu/Meu_SSD_subiu.md
> +Você seguiu o tutorial anterior, conseguiu “bootar” o SSD no seu computador, excelente! Mas… e agora?? ;-) Vamos aos primeiros passos, de forma bem detalhada (pensando em você que nunca usou linux an
alterado para [tutorial anterior](../recebi-meu-ssd/index.md)

2023-01-11 19:28 UTC, liciascl commented on docs/guias-infra/Meu_SSD_subiu/Meu_SSD_subiu.md
> +
done

2023-01-11 19:30 UTC, liciascl commented on docs/guias-infra/Meu_SSD_subiu/Meu_SSD_subiu.md
> +![Untitled](imgs/Untitled.png)
padronizando para img1, img2, ...

2023-01-11 19:31 UTC, liciascl commented on docs/guias-infra/Meu_SSD_subiu/Meu_SSD_subiu.md
> +A primeira configuração que recomendamos é trocar esta senha inicial. Para isso, você pode abrir o terminal (veja dois ícones de terminais na barra de atalhos). Você pode clicar no programa com o mou
O cuenca fez uma versão usando a interface gráfica tambem, achei legal padronizar o uso do terminator com super+T

2023-01-11 19:33 UTC, liciascl commented on docs/guias-infra/Meu_SSD_subiu/Meu_SSD_subiu.md
> +Algo que você precisa se habituar a usar é o terminal. Sim, no linux digitamos bastante e há algo importante neste caso, a tecla TAB é sua melhor amiga quando abrir o terminal! Ela sabe quase tudo!!
done

2023-01-13 00:46 UTC, merged