update informacoes principais
Insper/robotica-computacional pull request #54
Opened 2024-02-02 21:38 UTC by arnaldojr

2024-02-02 21:49 UTC, dsoldev requested changes

2024-02-02 21:49 UTC, dsoldev commented on docs/index.md
> -    * Módulo 8 - Controle
Controle Proporcional?

2024-02-03 00:20 UTC, arnaldojr commented on docs/index.md
> -    * Módulo 8 - Controle
ok

2024-02-03 02:23 UTC, dsoldev approved these changes

2024-02-03 02:23 UTC, merged